version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./letsencrypt-site:/usr/share/nginx/html
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
